# Kernel for UNIT-test of project.
.debug-configuration:

  # Windows 32-bit 2GB RAM (non-integrated GPU)
  gb2w32b: -XX:+CMSClassUnloadingEnabled -XX:+CMSPermGenSweepingEnabled -Xnoclassgc -XX:UseSSE=3 -Xincgc -Xmx768M -Xms512M -XX:PermSize=512M -XX:MaxPermSize=768M

  # Windows 64-bit 2GB RAM (integrated GPU)
  gb2w64b: -XX:+CMSClassUnloadingEnabled -XX:+CMSPermGenSweepingEnabled -Xnoclassgc -XX:UseSSE=3 -Xincgc -Xmx768M -Xms512M -XX:PermSize=512M -XX:MaxPermSize=768M

  # Windows 64-bit 4GB RAM
  gb4w64b: -XX:+CMSClassUnloadingEnabled -XX:+CMSPermGenSweepingEnabled -Xnoclassgc -XX:UseSSE=3 -Xincgc -Xmx2048M -Xms1024M -XX:PermSize=1024M -XX:MaxPermSize=2048M

  # Windows 64-bit 6GB RAM
  gb6w64b: -XX:+CMSClassUnloadingEnabled -XX:+CMSPermGenSweepingEnabled -Xnoclassgc -XX:UseSSE=3 -Xincgc -Xmx4096M -Xms2048M -XX:PermSize=2048M -XX:MaxPermSize=2048M

  # Windows 64-bit 10GB RAM
  gb10w64b: -XX:+CMSClassUnloadingEnabled -XX:+CMSPermGenSweepingEnabled -Xnoclassgc -XX:UseSSE=3 -Xincgc -Xmx6144M -Xms1024M -XX:PermSize=1024M -XX:MaxPermSize=2048M